site_name: My Docs
repo_url: https://gitlab;com/mon_projet
site_description: A test documentation
site_favicon: favicon.ico
copyright: 2016-loic
pages:
  - Home: index.md
theme: readthedocs
docs_dir: source
site_dir: site





